import Head from 'next/head'
import {ethers} from "ethers"
import { useEffect,useState } from 'react';
import Nft from './utils/Nft.json'

export default function Home() {

  const CONTRACT_ADDRESS = "0xf09b4A8B3C080471a25b1C527709639CbA15D54F";
  const [currentAccount,setCurrentAccount] = useState('');

  const checkIfWalletConnected = async () =>{

    const {ethereum} = window;
    
    if(!ethereum){
      console.log("Get Metamask");
    }else{
      console.log("Metamask Found");
    }

    const accounts = await ethereum.request({ method : 'eth_accounts'});

    if(accounts.length != 0){
      const account = accounts[0];
      console.log("Found authorized account",account);
      setCurrentAccount(account);
      setupEventListener()
    }else{
      console.log("No authorized account");
    }
  }

  const connectWallet = async () =>{

    try{  

      const {ethereum} = window;

      if(!ethereum){
        alert("Get metamask");
        return;
      }

      const accounts = await ethereum.request({method : 'eth_requestAccounts'});
      console.log("Connected", accounts[0]);
      setCurrentAccount(accounts[0]); 
      setupEventListener()
    }catch(error){
      console.log(error);
    }
  }

  const setupEventListener = async () => {
    try {
      const { ethereum } = window;

      if (ethereum) {
        const provider = new ethers.providers.Web3Provider(ethereum);
        const signer = provider.getSigner();
        const connectedContract = new ethers.Contract(CONTRACT_ADDRESS,Nft.abi, signer);

        connectedContract.on("NewEpicNFTMinted", (from, tokenId) => {
          console.log(from, tokenId.toNumber())
          alert(`Hey there! We've minted your NFT and sent it to your wallet. It may be blank right now. It can take a max of 10 min to show up on OpenSea. Here's the link: https://testnets.opensea.io/assets/${CONTRACT_ADDRESS}/${tokenId.toNumber()}`)
        });

        console.log("Setup event listener!")

      } else {
        console.log("Ethereum object doesn't exist!");
      }
    } catch (error) {
      console.log(error)
    }
  }

  const mintNft = async () =>{


    try{
      const {ethereum} = window;


      if(ethereum){
      const provider = new ethers.providers.Web3Provider(ethereum);
      const signer = provider.getSigner();
      const connectedContract = new ethers.Contract(CONTRACT_ADDRESS,Nft.abi,signer);

      console.log("Going to pop wallet now to pay gas...");
      let nftTxn = await connectedContract.makeNFT();

      console.log("Mining...please wait.")
      await nftTxn.wait();

      console.log(`Mined, see transaction: https://rinkeby.etherscan.io/tx/${nftTxn.hash}`);

      }else{
        console.log("Ethereum object doesn't exist!");
      }
    }catch(error){
      console.log(error);
    }
  }
    
  const renderNotConnectedContainer = () => (
    <button onClick={connectWallet} className="cta-button connect-wallet-button">
      Connect to Wallet
    </button>
  );

    useEffect(()=>{
      checkIfWalletConnected()
    },[])

  return (
    <div className="App">
      <Head>
        <title>NFT Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="header-container">
          <p className="header gradient-text">My NFT Collection</p>
          <p className="sub-text">
            Each unique. Each beautiful. Discover Your NFT Today.
          </p>
          {currentAccount === "" ? (
            renderNotConnectedContainer()
          ) : (
            <button onClick={mintNft} className="cta-button connect-wallet-button">
              Mint NFT
            </button>
          )}
        </div>
      </div>
    </div>
  )
}
